language: android

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
 - chmod +x gradlew

android:
  components:
    - build-tools-23.0.0
    - android-23

script:
  - ./gradlew clean check -Dpre-dex=false

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle